### ISSUE TITLE
图片等比例缩小显示变模糊解决方案

### ISSUE THREAD

**Issue by zhaodanli123** [zhaodanli123/mini-blog#48]
[MDN](https://developer.mozilla.org/zh-CN/docs/Web/CSS/image-rendering)<br>
``` css
img {
    image-rendering: -moz-crisp-edges; /* Firefox */
    image-rendering: -o-crisp-edges; /* Opera */
    image-rendering: -webkit-optimize-contrast; /* Webkit (non-standard naming) */
    image-rendering: crisp-edges;
    -ms-interpolation-mode: nearest-neighbor; /* IE (non-standard property) */
}
```
